### ISSUE TITLE
Glint does not read config from `extends` in `tsconfig.json`

### ISSUE THREAD

**Issue by cafreeman** [typed-ember/glint#549]
When extending a tsconfig that includes a glint configuration , glint doesn't follow the `extends` and, therefore, does not recognize that any config is present.

I've created a reproduction here: https://github.com/cafreeman/glint-extends-bug-repro

**Comment by chriskrycho** [comment]
Clarification—I *believe* this works correctly for local paths, based on this code:

https://github.com/typed-ember/glint/blob/3b0d3ab78765c2b39e25e09788597609740cacad/packages/core/src/config/loader.ts#L79

If I'm understanding correctly, both from that repro and from our discussion in chat, the issue is specifically that it does not follow an `extends` which points to a different *package*, right? Thus meaning that if we, say, set up a `@tsconfig/ember-with-glint`, it wouldn't be usable.

**Comment by NullVoxPopuli** [comment]
I think this is resolved, as all projects I'm aware of that use Glint extend from `@tsconfig/ember`, or some other in-monorepo custom config, such as `@my-place-of-work/tsconfig`.

**Comment by iarroyo** [comment]
We have faced this issue. We have a vertical micro frontend architecture, so we share some configurations across multiple Ember projects. 

We have observed that the glint configuration does not resolve correctly when a `tsconfig.json` file extends from a package.
To address this situation, we have considered the following three options:

a) Creates a [PR](https://github.com/typed-ember/glint/pull/781) to resolve tsconfig.json from a package (preferred one)
b) Resolve the tsconfig.json using a path (I would prefer not to go with this option)
```json
{
  "extends": "./node_modules/@package1/tsconfig.json"
}
```
c) Use the patch-package to patch glint to resolve tsconfig.json from a package
